const KEY='bt-cotizador-v3';
const defaultData={providers:[{id:'p1',name:'Proveedor 1',delivery:'Recogida presencial',shipping:0,note:''},{id:'p2',name:'Proveedor 2',delivery:'Envío',shipping:0,note:''}],repairs:['Pantalla OLED','Pantalla LCD','Batería','Puerto de carga','Flex de Encendido/Volumen','Cámara Trasera','Cámara Frontal','Altavoz / Parlante','Micrófono','Placa Base (diagnóstico)','IC de carga / soldadura','Cambio de vidrio (glass)','Sensor de huella','Face ID / sensores','Limpieza interna','Flex Carga'],references:[{id:'demo1',brand:'Xiaomi',model:'Redmi 10 2022',repair:'Pantalla LCD',quality:'LCD',providerId:'p1',cost:45000,note:'Ejemplo inicial. Reemplázalo por tu costo real.'}],history:[],settings:{laborLow:30000,laborMedium:40000,laborHigh:50000,marginMin:18,marginRec:30,marginPrem:45,rounding:1000}};
let data=load(),state={gama:'Media',quoteItems:[],pendingReferenceId:''};
function load(){try{const raw=localStorage.getItem(KEY);return raw?normalize(JSON.parse(raw)):structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function normalize(x){const d=structuredClone(defaultData);return {...d,...x,providers:Array.isArray(x.providers)?x.providers:d.providers,repairs:Array.isArray(x.repairs)?x.repairs:d.repairs,references:Array.isArray(x.references)?x.references:d.references,history:Array.isArray(x.history)?x.history:d.history,settings:{...d.settings,...(x.settings||{})}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Math.round(Number(v)||0))}
function roundPrice(v){const r=Number(data.settings.rounding)||1;return Math.round(v/r)*r}
function uid(p='id'){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function init(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));['quoteBrand','quoteModel'].forEach(id=>document.getElementById(id).addEventListener('input',updateQuoteReferences));document.getElementById('quoteRepair').addEventListener('change',()=>{state.pendingReferenceId='';updateQuoteReferences()});document.getElementById('laborCost').addEventListener('input',calculate);document.getElementById('addRepairBtn').addEventListener('click',addCurrentRepair);document.getElementById('saveQuoteBtn').addEventListener('click',saveQuote);document.getElementById('clearQuoteBtn').addEventListener('click',clearQuote);document.getElementById('newRefBtn').addEventListener('click',openReferenceDialog);document.getElementById('newProviderBtn').addEventListener('click',()=>document.getElementById('providerDialog').showModal());document.getElementById('referenceForm').addEventListener('submit',saveReferenceFromForm);document.getElementById('providerForm').addEventListener('submit',saveProviderFromForm);document.getElementById('searchRef').addEventListener('input',renderReferences);document.getElementById('saveConfigBtn').addEventListener('click',saveConfig);document.getElementById('exportBtn').addEventListener('click',exportData);document.getElementById('importInput').addEventListener('change',importData);document.getElementById('clearBtn').addEventListener('click',clearData);fillRepairs();fillConfig();renderProviders();renderReferences();renderHistory();updateDatalists();updateQuoteReferences()}
function showView(n){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${n}`));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===n));if(n==='catalogo')renderReferences();if(n==='proveedores')renderProviders();if(n==='historial')renderHistory()}
function fillRepairs(){document.getElementById('quoteRepair').innerHTML='<option value="">Selecciona...</option>'+data.repairs.map(r=>`<option value="${esc(r)}">${esc(r)}</option>`).join('')}
function updateDatalists(){document.getElementById('brandsList').innerHTML=[...new Set(data.references.map(r=>r.brand))].sort().map(x=>`<option value="${esc(x)}">`).join('');document.getElementById('modelsList').innerHTML=[...new Set(data.references.map(r=>r.model))].sort().map(x=>`<option value="${esc(x)}">`).join('')}
function laborForGama(){return state.gama==='Baja'?Number(data.settings.laborLow):state.gama==='Alta'?Number(data.settings.laborHigh):Number(data.settings.laborMedium)}
function currentMatches(){const b=document.getElementById('quoteBrand').value.trim().toLowerCase(),m=document.getElementById('quoteModel').value.trim().toLowerCase(),r=document.getElementById('quoteRepair').value;return data.references.filter(x=>(!b||x.brand.toLowerCase().includes(b))&&(!m||x.model.toLowerCase().includes(m))&&(!r||x.repair===r))}
function updateQuoteReferences(){const matches=currentMatches();renderProviderComparison(matches);document.getElementById('referenceInfo').textContent=matches.length?`${matches.length} referencia(s) encontrada(s). Selecciona una variante y luego agrégala al cálculo.`:'No hay referencias guardadas para esta búsqueda.';calculate()}
function renderProviderComparison(matches){const box=document.getElementById('providerComparison');if(!matches.length){box.innerHTML='';return}box.innerHTML='<div class="field-label">Variantes disponibles</div>'+matches.map(r=>{const p=data.providers.find(x=>x.id===r.providerId),shipping=Number(p?.shipping)||0,total=r.cost+shipping,already=state.quoteItems.some(i=>i.referenceId===r.id),selected=state.pendingReferenceId===r.id;const quality=r.quality?` · ${esc(r.quality)}`:'';return `<button type="button" class="provider-option ${selected?'selected':''} ${already?'added':''}" onclick="selectReference('${r.id}')"><span><strong>${esc(r.repair)}${quality}</strong><small>${esc(p?.name||'Sin proveedor')} · ${esc(p?.delivery||'')} · Repuesto ${money(r.cost)}${shipping?` · Envío ${money(shipping)}`:''}</small>${already?'<em>Ya agregado a esta cotización</em>':''}</span><strong>${money(total)}</strong></button>`}).join('')}
function selectReference(id){if(state.quoteItems.some(i=>i.referenceId===id)){alert('Esta referencia ya está agregada a la cotización.');return}state.pendingReferenceId=id;renderProviderComparison(currentMatches())}
function addCurrentRepair(){const id=state.pendingReferenceId;if(!id)return alert('Selecciona primero el repuesto que quieres usar.');const ref=data.references.find(r=>r.id===id);if(!ref)return;state.quoteItems.push({id:uid('q'),referenceId:id});state.pendingReferenceId='';renderSelectedRepairs();renderProviderComparison(currentMatches());calculate()}
function removeRepair(id){state.quoteItems=state.quoteItems.filter(i=>i.id!==id);renderSelectedRepairs();renderProviderComparison(currentMatches());calculate()}
function renderSelectedRepairs(){const box=document.getElementById('selectedRepairs');if(!state.quoteItems.length){box.innerHTML='';return}box.innerHTML='<div class="field-label">Reparaciones agregadas a esta cotización</div>'+state.quoteItems.map(i=>{const r=data.references.find(x=>x.id===i.referenceId),p=r&&data.providers.find(x=>x.id===r.providerId);return r?`<div class="selected-repair"><div><strong>${esc(r.repair)}${r.quality?` · ${esc(r.quality)}`:''}</strong><small>${esc(r.brand)} · ${esc(r.model)} · ${esc(p?.name||'Sin proveedor')}</small></div><strong>${money(r.cost+(Number(p?.shipping)||0))}</strong><button type="button" class="secondary" onclick="removeRepair('${i.id}')">Quitar</button></div>`:''}).join('')}
function quotePartsTotal(){return state.quoteItems.reduce((sum,i)=>{const r=data.references.find(x=>x.id===i.referenceId),p=r&&data.providers.find(x=>x.id===r.providerId);return sum+(r?.cost||0)+(Number(p?.shipping)||0)},0)}
function calculate(){const parts=quotePartsTotal(),labor=Number(document.getElementById('laborCost').value)||laborForGama(),base=parts+labor,min=roundPrice(base*(1+data.settings.marginMin/100)),rec=roundPrice(base*(1+data.settings.marginRec/100)),prem=roundPrice(base*(1+data.settings.marginPrem/100));document.getElementById('baseCost').value=money(base);document.getElementById('selectedCost').textContent=money(base);document.getElementById('priceMin').textContent=money(min);document.getElementById('priceRecommended').textContent=money(rec);document.getElementById('pricePremium').textContent=money(prem)}
function clearQuote(){state.quoteItems=[];state.pendingReferenceId='';['quoteBrand','quoteModel','laborCost'].forEach(id=>document.getElementById(id).value='');document.getElementById('quoteRepair').value='';document.getElementById('providerComparison').innerHTML='';document.getElementById('selectedRepairs').innerHTML='';document.getElementById('referenceInfo').textContent='Escribe marca, modelo y selecciona una reparación.';calculate()}
function saveQuote(){if(!state.quoteItems.length)return alert('Agrega al menos una reparación.');const base=quotePartsTotal()+(Number(document.getElementById('laborCost').value)||laborForGama());data.history.unshift({id:uid('h'),date:new Date().toISOString(),referenceIds:state.quoteItems.map(i=>i.referenceId),base,min:roundPrice(base*(1+data.settings.marginMin/100)),recommended:roundPrice(base*(1+data.settings.marginRec/100)),premium:roundPrice(base*(1+data.settings.marginPrem/100))});data.history=data.history.slice(0,100);save();renderHistory();alert('Cotización guardada.')}
function renderReferences(){const q=document.getElementById('searchRef').value.toLowerCase(),list=document.getElementById('referencesList'),rows=data.references.filter(r=>[r.brand,r.model,r.repair,r.quality,data.providers.find(p=>p.id===r.providerId)?.name].join(' ').toLowerCase().includes(q));if(!rows.length)return list.innerHTML='<div class="empty">No hay referencias que coincidan.</div>';list.innerHTML=rows.map(r=>{const p=data.providers.find(x=>x.id===r.providerId);return `<article class="list-card"><h3>${esc(r.brand)} · ${esc(r.model)}</h3><div class="meta">${esc(r.repair)} ${r.quality?`· ${esc(r.quality)}`:''}</div><div class="price-row"><div><div class="price">${money(r.cost)}</div><div class="meta">${esc(p?.name||'Sin proveedor')} · ${esc(p?.delivery||'')}</div></div></div>${r.note?`<div class="hint">${esc(r.note)}</div>`:''}</article>`}).join('')}
function openReferenceDialog(){document.getElementById('dialogProvider').innerHTML=data.providers.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');document.getElementById('referenceForm').reset();document.getElementById('referenceDialog').showModal()}
function saveReferenceFromForm(e){e.preventDefault();const f=new FormData(e.target),brand=f.get('brand').trim(),model=f.get('model').trim(),repair=f.get('repair').trim(),providerId=f.get('provider'),quality=f.get('quality').trim(),dup=data.references.find(r=>r.brand.toLowerCase()===brand.toLowerCase()&&r.model.toLowerCase()===model.toLowerCase()&&r.repair.toLowerCase()===repair.toLowerCase()&&r.providerId===providerId&&String(r.quality||'').toLowerCase()===quality.toLowerCase());if(dup){dup.cost=Number(f.get('cost'));dup.note=f.get('note').trim();alert('La referencia ya existía. Se actualizó su costo.')}else data.references.push({id:uid('r'),brand,model,repair,quality,providerId,cost:Number(f.get('cost')),note:f.get('note').trim()});save();e.target.closest('dialog').close();updateDatalists();renderReferences();fillRepairs();updateQuoteReferences()}
function renderProviders(){document.getElementById('providersList').innerHTML=data.providers.map(p=>`<article class="list-card"><h3>${esc(p.name)}</h3><div class="meta">${esc(p.delivery)} · Envío: ${money(p.shipping)}</div>${p.note?`<div class="hint">${esc(p.note)}</div>`:''}</article>`).join('')}
function saveProviderFromForm(e){e.preventDefault();const f=new FormData(e.target);data.providers.push({id:uid('p'),name:f.get('name').trim(),delivery:f.get('delivery'),shipping:Number(f.get('shipping'))||0,note:f.get('note').trim()});save();e.target.closest('dialog').close();renderProviders();updateQuoteReferences()}
function fillConfig(){document.getElementById('laborLow').value=data.settings.laborLow;document.getElementById('laborMedium').value=data.settings.laborMedium;document.getElementById('laborHigh').value=data.settings.laborHigh;document.getElementById('marginMin').value=data.settings.marginMin;document.getElementById('marginRec').value=data.settings.marginRec;document.getElementById('marginPrem').value=data.settings.marginPrem;document.getElementById('rounding').value=data.settings.rounding}
function saveConfig(){data.settings={laborLow:Number(document.getElementById('laborLow').value)||0,laborMedium:Number(document.getElementById('laborMedium').value)||0,laborHigh:Number(document.getElementById('laborHigh').value)||0,marginMin:Number(document.getElementById('marginMin').value)||0,marginRec:Number(document.getElementById('marginRec').value)||0,marginPrem:Number(document.getElementById('marginPrem').value)||0,rounding:Number(document.getElementById('rounding').value)||1};save();calculate();alert('Configuración guardada.')}
function renderHistory(){const list=document.getElementById('historyList');if(!data.history.length)return list.innerHTML='<div class="empty">Todavía no hay cálculos guardados.</div>';list.innerHTML=data.history.map(h=>{const refs=(h.referenceIds||[h.referenceId]).map(id=>data.references.find(x=>x.id===id)).filter(Boolean);return `<article class="list-card"><h3>${refs.length?esc(refs.map(r=>r.model).join(' + ')):'Cotización'}</h3><div class="meta">${esc(refs.map(r=>r.repair).join(' + '))} · ${new Date(h.date).toLocaleString('es-CO')}</div><div class="price-row"><span>Base ${money(h.base)}</span><strong>Recomendado ${money(h.recommended)}</strong></div></article>`}).join('')}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`black-tech-cotizador-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data=normalize(JSON.parse(reader.result));save();fillConfig();updateDatalists();renderProviders();renderReferences();renderHistory();updateQuoteReferences();alert('Respaldo importado.')}catch{alert('El archivo no tiene un formato válido.')}};reader.readAsText(file);e.target.value=''}
function clearData(){if(!confirm('¿Borrar todas las referencias, proveedores e historial de este dispositivo?'))return;localStorage.removeItem(KEY);data=structuredClone(defaultData);state.quoteItems=[];state.pendingReferenceId='';fillRepairs();fillConfig();updateDatalists();renderProviders();renderReferences();renderHistory();clearQuote()}
window.selectReference=selectReference;window.removeRepair=removeRepair;document.addEventListener('DOMContentLoaded',init);