/* V1.3: cotización robusta, mano de obra por reparación y total recomendado visible. */
(function(){
  const repairDefaults={'Pantalla OLED':65000,'Pantalla LCD':55000,'Batería':40000,'Puerto de carga':60000,'Flex de Encendido/Volumen':35000,'Cámara Trasera':40000,'Cámara Frontal':35000,'Altavoz / Parlante':35000,'Micrófono':35000,'Placa Base (diagnóstico)':30000,'IC de carga / soldadura':80000,'Cambio de vidrio (glass)':70000,'Sensor de huella':45000,'Face ID / sensores':50000,'Limpieza interna':30000,'Flex Carga':45000};
  function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Math.round(Number(v)||0));}
  function round(v){const r=Number(data.settings.rounding)||1000;return Math.round(v/r)*r;}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  function laborForRepair(){const repair=document.getElementById('quoteRepair')?.value||'';data.settings.repairLabor=data.settings.repairLabor||{};if(data.settings.repairLabor[repair]==null)data.settings.repairLabor[repair]=repairDefaults[repair]||50000;return Number(data.settings.repairLabor[repair])||0;}
  function selectedRef(){const id=document.getElementById('quoteReference')?.value||state.selectedReferenceId||'';return data.references.find(r=>r.id===id)||null;}
  function matches(){const b=(document.getElementById('quoteBrand')?.value||'').trim().toLowerCase(),m=(document.getElementById('quoteModel')?.value||'').trim().toLowerCase(),repair=document.getElementById('quoteRepair')?.value||'';return data.references.filter(r=>(!b||r.brand.toLowerCase().includes(b))&&(!m||r.model.toLowerCase().includes(m))&&(!repair||r.repair===repair));}
  function calculate(){const ref=selectedRef(),provider=ref?data.providers.find(p=>p.id===ref.providerId):null,part=Number(ref?.cost)||0,shipping=Number(provider?.shipping)||0,labor=Number(document.getElementById('laborCost')?.value)||laborForRepair(),base=part+shipping+labor,min=round(base*(1+Number(data.settings.marginMin||15)/100)),rec=round(base*(1+Number(data.settings.marginRec||30)/100)),prem=round(base*(1+Number(data.settings.marginPrem||45)/100));const set=(id,val)=>{const e=document.getElementById(id);if(e)e.textContent=money(val);};set('selectedCost',base);set('priceMin',min);set('priceRecommended',rec);set('pricePremium',prem);set('priceFinal',rec);const baseEl=document.getElementById('baseCost');if(baseEl)baseEl.value=money(base);}
  function renderProvidersComparison(){const box=document.getElementById('providerComparison'),hidden=document.getElementById('quoteReference');if(!box||!hidden)return;const rows=matches(),current=state.selectedReferenceId||hidden.value||'';hidden.innerHTML='<option value="">Selecciona...</option>'+rows.map(r=>`<option value="${r.id}">${esc(r.brand)} ${esc(r.model)} · ${esc(r.repair)}</option>`).join('');const chosen=rows.some(r=>r.id===current)?current:(rows[0]?.id||'');hidden.value=chosen;state.selectedReferenceId=chosen;box.innerHTML=rows.length?'<div class="field-label">Comparación de proveedores</div>'+rows.map(r=>{const p=data.providers.find(x=>x.id===r.providerId),ship=Number(p?.shipping)||0,total=Number(r.cost)+ship,active=r.id===chosen?' selected-provider':'';return `<button type="button" class="provider-card${active}" data-ref-id="${r.id}"><div><strong>${esc(p?.name||'Sin proveedor')}</strong><span>${esc(p?.delivery||'')} · Repuesto ${money(r.cost)}${ship?` · Envío ${money(ship)}`:''}</span></div><div><b>${money(r.cost)}</b><small>Total ${money(total)}</small></div></button>`;}).join(''):'<div class="empty">No hay referencias guardadas para esta búsqueda.</div>';box.querySelectorAll('[data-ref-id]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedReferenceId=btn.dataset.refId;hidden.value=btn.dataset.refId;renderProvidersComparison();calculate();}));const info=document.getElementById('referenceInfo');if(info)info.textContent=rows.length?`${rows.length} referencia(s) encontrada(s). Selecciona el proveedor que quieras usar.`:'No hay referencias guardadas para esta búsqueda. Puedes crear una desde “Referencias”.';}
  function setLaborFromRepair(force=true){const input=document.getElementById('laborCost');if(!input)return;const value=laborForRepair();if(force||!Number(input.value))input.value=value;}
  window.btSelectReference=function(id){const r=data.references.find(x=>x.id===id);if(!r)return;state.selectedReferenceId=id;document.getElementById('quoteBrand').value=r.brand;document.getElementById('quoteModel').value=r.model;document.getElementById('quoteRepair').value=r.repair;setLaborFromRepair(true);renderProvidersComparison();calculate();showView('cotizador');window.scrollTo({top:0,behavior:'smooth'});};
  window.btEditProvider=function(id){const p=data.providers.find(x=>x.id===id);if(!p)return;const name=prompt('Nombre del proveedor:',p.name);if(name===null)return;const delivery=prompt('Tipo de entrega (Recogida presencial / Envío / Ambos):',p.delivery);if(delivery===null)return;const shipping=prompt('Costo de envío:',p.shipping||0);if(shipping===null)return;const note=prompt('Nota:',p.note||'');if(note===null)return;p.name=name.trim()||p.name;p.delivery=delivery.trim()||p.delivery;p.shipping=Math.max(0,Number(shipping)||0);p.note=note.trim();save();renderProviders();renderProvidersComparison();calculate();};
  function addProviderButtons(){const list=document.getElementById('providersList');if(!list)return;list.querySelectorAll('.list-card').forEach((card,i)=>{if(card.querySelector('.edit-provider'))return;const p=data.providers[i];if(!p)return;const b=document.createElement('button');b.className='secondary full edit-provider';b.textContent='Editar proveedor';b.onclick=()=>btEditProvider(p.id);card.appendChild(b);});}
  function renderRepairLaborConfig(){data.settings.repairLabor=data.settings.repairLabor||{};data.repairs.forEach(r=>{if(data.settings.repairLabor[r]==null)data.settings.repairLabor[r]=repairDefaults[r]||50000;});let box=document.getElementById('repairLaborList');if(!box){const config=document.getElementById('marginMin')?.closest('.card');if(!config)return;box=document.createElement('div');box.id='repairLaborList';box.className='repair-labor-list';const title=document.createElement('div');title.className='section-title';title.textContent='Mano de obra por reparación';const help=document.createElement('p');help.className='muted';help.textContent='Define cuánto quieres considerar como mano de obra base para cada reparación.';const marginTitle=document.querySelector('#marginMin')?.closest('.card')?.querySelector('.section-title');config.insertBefore(title,marginTitle);config.insertBefore(help,marginTitle);config.insertBefore(box,marginTitle);}box.innerHTML=data.repairs.map((r,i)=>`<label>${esc(r)}<input class="repair-labor-input" data-repair-index="${i}" type="number" min="0" step="1000" value="${Number(data.settings.repairLabor[r])||0}"></label>`).join('');}
  function saveRepairLaborConfig(){document.querySelectorAll('.repair-labor-input').forEach(input=>{const r=data.repairs[Number(input.dataset.repairIndex)];if(r)data.settings.repairLabor[r]=Math.max(0,Number(input.value)||0);});}
  function addStyles(){if(document.getElementById('bt-v13-styles'))return;const s=document.createElement('style');s.id='bt-v13-styles';s.textContent='.provider-card{width:100%;border:1px solid #dfe3e8;background:#fff;border-radius:12px;padding:13px;margin-top:8px;display:flex;align-items:center;justify-content:space-between;gap:12px;text-align:left;cursor:pointer;font:inherit;color:#172033}.provider-card.selected-provider{border:2px solid #2563eb;background:#eff6ff}.provider-card span{display:block;color:#6b7280;font-size:12px;margin-top:3px}.provider-card b{font-size:17px;white-space:nowrap}.provider-card small{display:block;color:#6b7280;font-size:11px;margin-top:2px}.edit-provider{margin-top:12px}.repair-labor-list{display:grid;gap:10px;margin-bottom:18px}.repair-labor-list label{display:grid;grid-template-columns:1fr 150px;align-items:center;gap:10px}.final-price{background:#111827;color:#fff;border-radius:14px;padding:18px;margin:0 0 14px;display:flex;align-items:center;justify-content:space-between;gap:16px}.final-price span{font-weight:700}.final-price strong{font-size:30px}@media(max-width:700px){.repair-labor-list label{grid-template-columns:1fr}.final-price{align-items:flex-start;flex-direction:column}.final-price strong{font-size:28px}}';document.head.appendChild(s);}
  function initPatch(){addStyles();data.settings.repairLabor=data.settings.repairLabor||{};data.repairs.forEach(r=>{if(data.settings.repairLabor[r]==null)data.settings.repairLabor[r]=repairDefaults[r]||50000;});data.settings.marginMin ??=15;data.settings.marginRec ??=30;data.settings.marginPrem ??=45;data.settings.rounding ??=1000;renderRepairLaborConfig();['quoteBrand','quoteModel'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>{renderProvidersComparison();calculate();}));document.getElementById('quoteRepair')?.addEventListener('change',()=>{setLaborFromRepair(true);renderProvidersComparison();calculate();});document.getElementById('laborCost')?.addEventListener('input',calculate);document.getElementById('saveConfigBtn')?.addEventListener('click',()=>{saveRepairLaborConfig();data.settings.marginMin=Math.max(0,Number(document.getElementById('marginMin')?.value)||15);data.settings.marginRec=Math.max(0,Number(document.getElementById('marginRec')?.value)||30);data.settings.marginPrem=Math.max(0,Number(document.getElementById('marginPrem')?.value)||45);data.settings.rounding=Math.max(1,Number(document.getElementById('rounding')?.value)||1000);save();renderRepairLaborConfig();setLaborFromRepair(true);calculate();});document.getElementById('referencesList')?.addEventListener('click',e=>{const b=e.target.closest('button[onclick^="useReference"]');if(b){e.preventDefault();const m=b.getAttribute('onclick')?.match(/'([^']+)'/);if(m)btSelectReference(m[1]);}});document.querySelector('[data-view="proveedores"]')?.addEventListener('click',()=>setTimeout(addProviderButtons,50));document.getElementById('newProviderBtn')?.addEventListener('click',()=>setTimeout(addProviderButtons,100));setTimeout(()=>{renderProvidersComparison();setLaborFromRepair(false);calculate();addProviderButtons();},200);}
  document.addEventListener('DOMContentLoaded',initPatch);
})();
