/* V1.9 - Cotizacion multi-reparacion + costo real + mano de obra combinada */
(function(){
  const repairDefaults={'Pantalla OLED':65000,'Pantalla LCD':55000,'Batería':40000,'Puerto de carga':60000,'Flex de Encendido/Volumen':35000,'Cámara Trasera':40000,'Cámara Frontal':35000,'Altavoz / Parlante':35000,'Micrófono':35000,'Placa Base (diagnóstico)':30000,'IC de carga / soldadura':80000,'Cambio de vidrio (glass)':70000,'Sensor de huella':45000,'Face ID / sensores':50000,'Limpieza interna':30000,'Flex Carga':45000};
  const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Math.round(Number(v)||0));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let items=[];
  function laborFor(r){data.settings.repairLabor=data.settings.repairLabor||{};if(data.settings.repairLabor[r]==null)data.settings.repairLabor[r]=repairDefaults[r]||50000;return Number(data.settings.repairLabor[r])||0}
  function currentRef(){const id=document.getElementById('quoteReference')?.value||state.selectedReferenceId;return data.references.find(r=>r.id===id)||null}
  function providerCost(ref){const p=data.providers.find(x=>x.id===ref.providerId);const ship=Number(p?.shipping)||0;const travel=Number(p?.travelCost)||0;const delivery=(p?.delivery||'').toLowerCase();const trip=delivery.includes('recogida')?travel:0;return {p,ship,travel:trip,total:Number(ref.cost||0)+ship+trip}}
  function combinedLabor(){if(!items.length)return 0;const vals=items.map(it=>Number(it.labor)||0).filter(v=>v>0);if(vals.length<=1)return vals[0]||0;const max=Math.max(...vals),others=vals.reduce((a,v)=>a+v,0)-max;return Math.round((max+others*0.5)/1000)*1000}
  function renderItems(){const box=document.getElementById('quoteItems');if(!box)return;if(!items.length){box.innerHTML='<div class="empty">Aún no hay reparaciones agregadas. Selecciona una referencia y pulsa “Agregar reparación”.</div>';return}box.innerHTML=items.map((it,i)=>{const c=providerCost(it.ref),labor=Number(it.labor)||0;return `<div class="quote-item"><div><strong>${esc(it.ref.repair)}</strong><span>${esc(it.ref.brand)} · ${esc(it.ref.model)} · ${esc(c.p?.name||'Sin proveedor')}</span><span>Repuesto ${money(it.ref.cost)}${c.travel?` · Desplazamiento ${money(c.travel)}`:''}</span></div><div class="quote-item-right"><b>${money(c.total)}</b><small>Base de mano de obra ${money(labor)}</small><button type="button" class="danger small-remove" data-remove="${i}">Quitar</button></div></div>`}).join('');box.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{items.splice(Number(b.dataset.remove),1);renderItems();calculateAll()}))}
  function calculateAll(){const laborInput=document.getElementById('laborCost');const single=currentRef();if(!items.length&&single){const labor=Number(laborInput?.value)||laborFor(single.repair);items=[{ref:single,labor}];}
    let parts=0,travel=0,shipping=0;items.forEach(it=>{const c=providerCost(it.ref);parts+=Number(it.ref.cost)||0;shipping+=c.ship;travel+=c.travel});
    const labor=combinedLabor();const base=parts+shipping+travel+labor;const s=data.settings||{};const min=round(base*(1+Number(s.marginMin??15)/100));const rec=round(base*(1+Number(s.marginRec??30)/100));const prem=round(base*(1+Number(s.marginPrem??45)/100));
    const put=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=money(v)};put('partsCost',parts);put('travelCostTotal',travel);put('shippingCostTotal',shipping);put('laborTotal',labor);put('selectedCost',base);put('priceMin',min);put('priceRecommended',rec);put('pricePremium',prem);put('priceFinal',rec);const bc=document.getElementById('baseCost');if(bc)bc.value=money(base);
    const breakdown=document.getElementById('quoteBreakdown');if(breakdown)breakdown.innerHTML=items.length?`<div>Repuestos <strong>${money(parts)}</strong></div><div>Mano de obra <strong>${money(labor)}</strong>${items.length>1?`<small class="labor-note">(ajustada por trabajos combinados)</small>`:''}</div>${travel?`<div>Desplazamiento <strong>${money(travel)}</strong></div>`:''}${shipping?`<div>Envíos <strong>${money(shipping)}</strong></div>`:''}<div class="breakdown-total">Costo real <strong>${money(base)}</strong></div>`:'';
    renderProviderChoice();
  }
  function renderProviderChoice(){const box=document.getElementById('smartProvider');if(!box)return;const ref=currentRef();if(!ref){box.innerHTML='';return}const matches=data.references.filter(r=>r.brand.toLowerCase()===ref.brand.toLowerCase()&&r.model.toLowerCase()===ref.model.toLowerCase()&&r.repair===ref.repair);const rows=matches.map(r=>{const c=providerCost(r);return {r,c}}).sort((a,b)=>a.c.total-b.c.total);if(rows.length<2){box.innerHTML='';return}const best=rows[0];box.innerHTML=`<div class="smart-provider"><strong>Proveedor más conveniente para esta referencia</strong><span>${esc(best.c.p?.name||'Sin proveedor')} · costo efectivo ${money(best.c.total)}</span></div>`;}
  function addCurrent(){const ref=currentRef();if(!ref){alert('Selecciona una referencia primero.');return}if(items.some(x=>x.ref.id===ref.id)){alert('Esta referencia ya está agregada.');return}const labor=Number(document.getElementById('laborCost')?.value)||laborFor(ref.repair);items.push({ref,labor});document.getElementById('laborCost').value='';renderItems();calculateAll()}
  function clearAll(){items=[];['quoteBrand','quoteModel','laborCost','quoteReference'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const repair=document.getElementById('quoteRepair');if(repair)repair.value='';state.selectedReferenceId='';['quoteItems','providerComparison','smartProvider'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=''});const info=document.getElementById('referenceInfo');if(info)info.textContent='Escribe marca y modelo para buscar referencias guardadas.';['baseCost','partsCost','travelCostTotal','shippingCostTotal','laborTotal'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=money(0),e.textContent=money(0)});['selectedCost','priceMin','priceRecommended','pricePremium','priceFinal'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=money(0)});renderItems();document.getElementById('quoteBrand')?.focus()}
  function enhanceProviders(){data.providers.forEach(p=>{if(p.travelCost==null)p.travelCost=0});const list=document.getElementById('providersList');if(!list)return;list.querySelectorAll('.list-card').forEach((card,i)=>{const p=data.providers[i];if(!p||card.querySelector('.travel-badge'))return;const d=document.createElement('div');d.className='hint travel-badge';d.textContent=(p.delivery||'').toLowerCase().includes('recogida')?`Desplazamiento estimado: ${money(p.travelCost)}`:'Sin desplazamiento: entrega a domicilio';card.appendChild(d);const b=card.querySelector('.edit-provider');if(b){b.onclick=()=>editProvider(p)}else{const eb=document.createElement('button');eb.className='secondary full edit-provider';eb.textContent='Editar proveedor';eb.onclick=()=>editProvider(p);card.appendChild(eb)}})}
  function editProvider(p){const n=prompt('Nombre del proveedor:',p.name);if(n===null)return;const d=prompt('Tipo de entrega (Recogida presencial / Envío / Ambos):',p.delivery);if(d===null)return;const s=prompt('Costo de envío:',p.shipping||0);if(s===null)return;const t=prompt('Costo estimado de desplazamiento para recoger:',p.travelCost||0);if(t===null)return;const note=prompt('Nota:',p.note||'');if(note===null)return;p.name=n.trim()||p.name;p.delivery=d.trim()||p.delivery;p.shipping=Math.max(0,Number(s)||0);p.travelCost=Math.max(0,Number(t)||0);p.note=note.trim();save();renderProviders();setTimeout(enhanceProviders,50);calculateAll()}
  function inject(){if(document.getElementById('quoteItems'))return;const form=document.querySelector('#view-cotizador .card');if(!form)return;const ref=document.getElementById('quoteReference');if(ref){const wrap=ref.parentElement;wrap.style.display='none'}const add=document.createElement('button');add.type='button';add.className='secondary full';add.id='addRepairBtn';add.textContent='+ Agregar reparación a esta cotización';add.onclick=addCurrent;const cmp=document.getElementById('providerComparison');cmp?.parentElement?.insertBefore(add,cmp.nextSibling);const itemsBox=document.createElement('div');itemsBox.id='quoteItems';itemsBox.className='quote-items';add.parentElement?.insertBefore(itemsBox,document.getElementById('referenceInfo'));const breakdown=document.createElement('div');breakdown.id='quoteBreakdown';breakdown.className='quote-breakdown';const results=document.querySelector('#view-cotizador .results-card');if(results)results.insertBefore(breakdown,results.querySelector('.result-grid'));const smart=document.createElement('div');smart.id='smartProvider';results?.insertBefore(smart,breakdown);items=[];renderItems();}
  function style(){if(document.getElementById('v19-style'))return;const s=document.createElement('style');s.id='v19-style';s.textContent='.quote-items{display:grid;gap:10px;margin:14px 0}.quote-item{background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:14px;display:flex;justify-content:space-between;gap:14px}.quote-item span{display:block;color:#6b7280;font-size:12px;margin-top:3px}.quote-item-right{text-align:right}.quote-item-right b{display:block;font-size:18px}.quote-item-right small{display:block;color:#6b7280}.small-remove{padding:6px 9px!important;font-size:12px!important;margin-top:6px}.quote-breakdown{display:grid;gap:8px;margin:0 0 14px;background:#f8fafc;border-radius:14px;padding:14px}.quote-breakdown>div{display:flex;justify-content:space-between;color:#6b7280;gap:10px}.quote-breakdown .breakdown-total{border-top:1px solid #dfe3e8;padding-top:10px;color:#172033;font-weight:800}.labor-note{display:block;font-size:11px;color:#64748b;margin-left:6px}.smart-provider{background:#ecfdf5;border:1px solid #a7f3d0;color:#065f46;border-radius:14px;padding:13px;margin-bottom:14px}.smart-provider span{display:block;margin-top:4px}.travel-badge{margin-top:10px}.provider-option small{line-height:1.4}@media(max-width:700px){.quote-item{align-items:flex-start}.quote-item-right{min-width:110px}.quote-item-right b{font-size:16px}}';document.head.appendChild(s)}
  document.addEventListener('DOMContentLoaded',()=>{style();setTimeout(()=>{inject();enhanceProviders();const b=document.getElementById('clearQuoteBtn');b?.addEventListener('click',clearAll,true);['quoteBrand','quoteModel','quoteRepair','quoteReference','laborCost'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>setTimeout(calculateAll,20)));document.getElementById('quoteRepair')?.addEventListener('change',()=>setTimeout(calculateAll,20));document.getElementById('quoteReference')?.addEventListener('change',()=>setTimeout(calculateAll,20));renderItems();calculateAll()},150)});
})();
